name = chainworld
title = ChainWorld - On-Chain World Sync
description = Records all world events on-chain via middleware, enabling a persistent on-chain managed world.
author = chainworld
optional_depends = default
